#!/usr/bin/ruby

# == ao-qc - The Agent-Orange Cue-Cleaner
# Author:: Jamie Hardt

# This file is part of "agent-orange".
# 
# "agent-orange" is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# "agent-orange" is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with "agent-orange"; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

lib_path = File.dirname(__FILE__) + "/lib/"
$: << lib_path

APP_NAME = "ao-qc"
APP_AUTHOR = "Jamie Hardt"
APP_LONG_VERSION = "Version 0.1 2006-06-09"
APP_VERSION = 0.1


begin
  require 'rubygems'
  require 'pt/session'

  require 'pathname'
  require 'ostruct'
  require 'optparse'

  include PT
rescue
  $stderr.print "An error occurred while loading qs libraries, \
    you may have an old version of the ruby interpreter.\n"
  exit 17001
end

cli_options = OpenStruct.new(:blend_duration => 1.0,
                             :min_closed_cue_length => 1.0,
                             :interpret_tagging => true )

opts = OptionParser.new do |opts|
  
  opts.banner =  "Usage: ao-qc [OPTIONS] file"
  opts.separator "The Agent-Orange Cue-Cleaner, a script for pre-processing"
  opts.separator "text files formatted for cuesheeting."
  opts.separator ""
  
  opts.on("-b SECONDS","--blend-duration=SECONDS",Float,"Blend regions which occur",
                                                       "within this duration.") do |v|
    cli_options.blend_duration = v
  end
                                                         
  opts.on("-m SECONDS","--min-closed-cue-length=SECONDS", Float,"Minimum closed cue length.") do |v|
    cli_options.min_closed_cue_length = v
  end

  opts.on("-i","--ignore-tagging", "Ignore tagging.") do
    cli_options.interpret_tagging = false
  end


  opts.on_tail("-h","--help","Show this message.") do
    puts opts
    exit 0
  end                                                    
end #OptionParser

##$stderr.print "Starting cuesheet\n"
begin
  rest = opts.parse!($*)
rescue
  puts opts 
  exit 1
end

rest.each do |path|

  a_session = Session.new

  begin
    File.open(path,"r") do |file|
      a_session.read_file(file)
      
      a_session.interpret_tagging! if cli_options.interpret_tagging
      
      puts a_session.to_text_export

    end #File.open
  rescue SystemCallError
      $stderr.print "An error ocurred opening the file : " + $! + "\n"
      exit 4
  end
end
